-- MySQL Script generated by MySQL Workbench
-- Tue 19 Dec 2017 03:42:06 PM AKST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL DEFAULT 1000,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email_address` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(15) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`blog_topics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`blog_topics` ;

CREATE TABLE IF NOT EXISTS `mydb`.`blog_topics` (
  `id` INT NOT NULL DEFAULT 1000,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`blog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`blog` ;

CREATE TABLE IF NOT EXISTS `mydb`.`blog` (
  `id` INT NOT NULL DEFAULT 1000,
  `title` VARCHAR(45) NOT NULL,
  `body` LONGTEXT NOT NULL,
  `post_time` DATE NOT NULL,
  `user_id` INT NOT NULL,
  `blog_topics_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_blog_user_idx` (`user_id` ASC),
  INDEX `fk_blog_blog_topics1_idx` (`blog_topics_id` ASC),
  CONSTRAINT `fk_blog_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_blog_blog_topics1`
    FOREIGN KEY (`blog_topics_id`)
    REFERENCES `mydb`.`blog_topics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`blog_comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`blog_comments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`blog_comments` (
  `blog_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `comment` MEDIUMTEXT NOT NULL,
  `comment_time` DATE NOT NULL,
  PRIMARY KEY (`blog_id`, `user_id`),
  INDEX `fk_blog_has_user_user1_idx` (`user_id` ASC),
  INDEX `fk_blog_has_user_blog1_idx` (`blog_id` ASC),
  CONSTRAINT `fk_blog_has_user_blog1`
    FOREIGN KEY (`blog_id`)
    REFERENCES `mydb`.`blog` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_blog_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
